/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:746c4c23-172c-4d94-81af-a259d76c5485",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_T4K5BwFSb",
    "aws_user_pools_web_client_id": "3qa5a626a6sv077vh9orjrrm1b",
    "oauth": {
        "domain": "noteapptesttttoath-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "myapp://",
        "redirectSignOut": "myapp://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
